version: "3.9"

services:
  db:
    image: postgres:16
    container_name: emopet-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: emopet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0910
    ports:
      - "5432:5432"
    volumes:
      - emopet_pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: emopet-backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/emopet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0910
      # (по желанию) чтобы Hibernate само создавало таблицы на старте:
      # SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  emopet_pgdata: